config/routes.rb
FirehoseHbs::Application.routes.draw do

  root 'static_pages#index'
  resources :pics

end

app/models/pic.rb
	class Pic < ActiveRecord::Base
		mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController

	def index
		@pics = Pic.all
	end

	def new
		@pic = Pic.new
	end

	def create
		@pics = Pic.create( pic_params )
		redirect_to pics_path
	end	


	private

	def pic_params
	params.require(:pic).permit(:lesson, :emotion, :learned, :image)
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def index
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FirehoseHbs</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	    <div class="navbar navbar-inverse">
    <div class="navbar-inner">
    <div class="container">
     
    <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    </a>
     
    <!-- Be sure to leave the brand out there if you want it shown -->
     
    <%= link_to 'Firehose App', root_path, :class => 'brand' %>

    <!-- Everything you want hidden at 940px or less, place within here -->
    <div class="nav-collapse collapse">
    <!-- .nav, .navbar-search, .navbar-form, etc -->
		<ul class="nav">
			<li>
				<%= link_to 'My App', pics_path %>
			</li>
            <li>
                <%= link_to 'Create New', new_pic_path %>
            </li>
		</ul>

    </div>
     
    </div>
    </div>
    </div>

<%= yield %>

</body>
</html>

app/views/pics/index.html.erb
<% @pics.each do |pic| %>
	
<div class="span4 boxy text-center">

	<h1 class="h1-custom"> 
		Lesson: <%= pic.lesson %>
	</h1>

	<%= image_tag pic.image %>

	<br />
	<h2> 
		Emotion: <%= pic.emotion %>
		<br />
	
		Learned: <%= pic.learned %>
		<br />
	</h2>
	
</div>

<% end %>

app/views/pics/new.html.erb
<div class="span 6 offset3 boxy text-center">
	<h1 class="h1-custom">
		Upload lesson
	</h1>
	<br />
	<%= simple_form_for @pic do |f| %>
	 
	  <%= f.input :lesson, label: 'Your Latest Lesson', :placeholder => '1, 2, etc.' %>

	  <%= f.input :image %>

	  <%= f.input :emotion, label: 'How did you feel?', :placeholder => 'Stoked, Happy or Jazzed' %>
	  
	  <%= f.input :learned, label: 'Lesson Learned', :placeholder => 'HTML5, CSS3, Rails, Github, etc.' %>
	  <br />
	  <%= submit_tag 'Save', :class => 'btn btn-warning btn-large' %>

	<% end %>

</div>

app/views/static_pages/index.html.erb
<div class="span6 offset3 boxy text-center">
	
	<h1 class=h1-custom>Hi I'm Elise</h1>

	<br/>

	<h2>Welcome to my app!</h2>

	<br/>

	<h3 class=h3-custom>Click here to launch app</h3>

	<br/>
	<br/>
	
	<%= link_to 'Launch', pics_path, :class=> 'btn btn-warning btn-large' %>

</div>